# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: windows-latest

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 6'
    inputs:
      packageType: sdk
      version: '6.0.x'

  - task: UseDotNet@2
    displayName: 'Use .NET 7 Preview'
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'nuget restore'
    inputs:
      command: restore
      projects: '**/*.csproj'
      configuration: $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      projects: '**/*.csproj'
      configuration: $(BuildConfiguration)
      
# TODO: Run tests      
#  - task: DotNetCoreCLI@2
#    displayName: 'dotnet test'
#    inputs:
#      command: test
#      projects: '**/*.csproj'
#
