# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- preview

pr: none

pool:
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU|x86|x64|ARM|ARM64'
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 6'
    inputs:
      packageType: sdk
      version: '6.0.x'

  - task: UseDotNet@2
    displayName: 'Use .NET 7 Preview'
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'nuget restore'
    inputs:
      command: restore
      projects: '**/*.csproj'
      configuration: $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: '**/*.csproj'
      nobuild: false
      includesymbols: true
      versioningScheme: 'off'
      configuration: $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: 'nuget push'
    inputs:
      command: custom
      custom: nuget
      arguments: >
        push "$(Build.ArtifactStagingDirectory)\*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k $(key)
        --skip-duplicate
